<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<!DOCTYPE DATABASE [
        <!ELEMENT EMPLOYEE (SURNAME|NAME|PATRONYMIC|ADDRESS|NUMBER|POSITION|SUBVISION)*>
        <!ELEMENT SURNAME (#PCDATA)>
        <!ELEMENT NAME (#PCDATA)>
        <!ELEMENT PATRONYMIC (#PCDATA)>
        <!ELEMENT POSITION (#PCDATA)>
        <!ELEMENT SUBVISION (#PCDATA)>
        <!ELEMENT NUMBER (HOME|PHONE)*>
        <!ELEMENT HOME (#PCDATA)>
        <!ELEMENT PHONE (#PCDATA)>
        <!ELEMENT ADDRESS (INDEX|TYPESETTLEMENT|REGION|DISTRICT|NAMESETTLEMENT|SREET|NUMBERHOME|HOUSING|ROOM)*>
        <!ELEMENT INDEX (#PCDATA)>
        <!ELEMENT TYPESETTLEMENT (#PCDATA)>
        <!ELEMENT REGION (#PCDATA)>
        <!ELEMENT DISTRICT (#PCDATA)>
        <!ELEMENT NAMESETTLEMENT (#PCDATA)>
        <!ELEMENT SREET (#PCDATA)>
        <!ELEMENT NUMBERHOME (#PCDATA)>
        <!ELEMENT HOUSING (num)>
        <!ATTLIST num
                id CDATA #IMPLIED>
        <!ELEMENT ROOM (#PCDATA)>
        ]>
<DATABASE>
<EMPLOYEE>
	<SURNAME>Смирнова</SURNAME>
	<NAME>Виктория</NAME>
	<PATRONYMIC>Игоревна</PATRONYMIC>
	<ADDRESS>
		<INDEX>65125</INDEX>
		<TYPESETTLEMENT>Город</TYPESETTLEMENT>
		<REGION>Одесская область</REGION>
		<DISTRICT>Одесский район</DISTRICT>
		<NAMESETTLEMENT>Одесса</NAMESETTLEMENT>
		<SREET>Платанова</SREET>
		<NUMBERHOME>2</NUMBERHOME>
		<HOUSING>2</HOUSING>
		<ROOM>45</ROOM>
	</ADDRESS>
	<NUMBER>
		<HOME>05761 177 84 12</HOME>
		<PHONE>+38 05761 844 10 99</PHONE>
	</NUMBER>
	<POSITION>Секретарь</POSITION>
	<SUBVISION>Бухгалтерия</SUBVISION>
</EMPLOYEE>
<EMPLOYEE>
	<SURNAME>Иванов</SURNAME>
	<NAME>Сергей</NAME>
	<PATRONYMIC>Валентинович</PATRONYMIC>
	<ADDRESS>
		<INDEX>65125</INDEX>
		<TYPESETTLEMENT>Поселок</TYPESETTLEMENT>
		<REGION>Одесская область</REGION>
		<DISTRICT>Одесский район</DISTRICT>
		<NAMESETTLEMENT>Ильичевск</NAMESETTLEMENT>
		<SREET>Молодежная</SREET>
		<NUMBERHOME>18</NUMBERHOME>
		<ROOM>23</ROOM>
	</ADDRESS>
	<NUMBER>
		<HOME>05761 177 84 12</HOME>
		<PHONE>+38 05761 444 23 19</PHONE>
		<PHONE>+38 05761 844 10 99</PHONE>
	</NUMBER>
	<POSITION>Менеджер</POSITION>
	<SUBVISION>Административное</SUBVISION>
</EMPLOYEE>
<EMPLOYEE>
	<SURNAME>Никитина</SURNAME>
	<NAME>Светлана</NAME>
	<PATRONYMIC>Алексеевна</PATRONYMIC>
	<ADDRESS>
		<INDEX>65125</INDEX>
		<TYPESETTLEMENT>деревня</TYPESETTLEMENT>
		<REGION>Одесская область</REGION>
		<DISTRICT>Болградский район</DISTRICT>
		<NAMESETTLEMENT>Малиновка</NAMESETTLEMENT>
		<SREET>Школьная</SREET>
		<NUMBERHOME>20</NUMBERHOME>
		<ROOM>-</ROOM>
	</ADDRESS>
	<NUMBER>
		<HOME>05761 177 84 12</HOME>
		<PHONE>+38 05761 844 10 99</PHONE>
	</NUMBER>
	<POSITION>Бухгалтер</POSITION>
	<SUBVISION>Бухгалтерия</SUBVISION>
</EMPLOYEE>
<EMPLOYEE>
	<SURNAME>Сидоров</SURNAME>
	<NAME>Анатолий</NAME>
	<PATRONYMIC>Степанович</PATRONYMIC>
	<ADDRESS>
		<INDEX>65125</INDEX>
		<TYPESETTLEMENT>Город</TYPESETTLEMENT>
		<REGION>Одесская область</REGION>
		<DISTRICT>Одесский район</DISTRICT>
		<NAMESETTLEMENT>Одесса</NAMESETTLEMENT>
		<SREET>Платанова</SREET>
		<NUMBERHOME>18</NUMBERHOME>
		<ROOM>23</ROOM>
	</ADDRESS>
	<NUMBER>
		<HOME>05761 177 84 12</HOME>
		<PHONE>+38 05761 444 23 19</PHONE>
		<PHONE>+38 05761 844 10 99</PHONE>
	</NUMBER>
	<POSITION>Аналитик</POSITION>
	<SUBVISION>Маркетинг</SUBVISION>
</EMPLOYEE>
	<EMPLOYEE>
	<SURNAME>Зайцев</SURNAME>
	<NAME>Иван</NAME>
	<PATRONYMIC>Сергеевич</PATRONYMIC>
	<ADDRESS>
		<INDEX>65125</INDEX>
		<TYPESETTLEMENT>Город</TYPESETTLEMENT>
		<REGION>Днепропетровская область</REGION>
		<DISTRICT>Криворожский район</DISTRICT>
		<NAMESETTLEMENT>Кривой Рог</NAMESETTLEMENT>
		<SREET>Героев АТО</SREET>
		<NUMBERHOME>31</NUMBERHOME>
		<HOUSING>2</HOUSING>
		<ROOM>20</ROOM>
	</ADDRESS>
	<NUMBER>
		<HOME>05761 177 84 12</HOME>
		<PHONE>+38 05761 844 10 99</PHONE>
	</NUMBER>
	<POSITION>Вэб-аналитик</POSITION>
	<SUBVISION>Маркетинг</SUBVISION>
</EMPLOYEE>
<EMPLOYEE>
	<SURNAME>Петров</SURNAME>
	<NAME>Сергей</NAME>
	<PATRONYMIC>Викторович</PATRONYMIC>
	<ADDRESS>
		<INDEX>65125</INDEX>
		<TYPESETTLEMENT>Poselok</TYPESETTLEMENT>
		<REGION>Одесская область</REGION>
		<DISTRICT>Одесский район</DISTRICT>
		<NAMESETTLEMENT>Ильичевск</NAMESETTLEMENT>
		<SREET>Молодежная</SREET>
		<NUMBERHOME>24</NUMBERHOME>
		<ROOM>19</ROOM>
	</ADDRESS>
	<NUMBER>
		<HOME>05761 177 84 12</HOME>
		<PHONE>+38 05761 444 23 19</PHONE>
		<PHONE>+38 05761 844 10 99</PHONE>
	</NUMBER>
	<POSITION>Бухгалтер</POSITION>
	<SUBVISION>Расчётный отдел</SUBVISION>
</EMPLOYEE>
<EMPLOYEE>
	<SURNAME>Богданов</SURNAME>
	<NAME>Алексей</NAME>
	<PATRONYMIC>Сергеевич</PATRONYMIC>
	<ADDRESS>
		<INDEX>65125</INDEX>
		<TYPESETTLEMENT>Город</TYPESETTLEMENT>
		<REGION>Одесская область</REGION>
		<DISTRICT>Болградский район</DISTRICT>
		<NAMESETTLEMENT>Болград</NAMESETTLEMENT>
		<SREET>Цирк</SREET>
		<NUMBERHOME>20</NUMBERHOME>
		<ROOM>17</ROOM>
	</ADDRESS>
	<NUMBER>
		<HOME>05761 177 84 12</HOME>
		<PHONE>+38 05761 844 10 99</PHONE>
	</NUMBER>
	<POSITION>Бухгалтер</POSITION>
	<SUBVISION>Отдел кадров</SUBVISION>
</EMPLOYEE>
<EMPLOYEE>
	<SURNAME>Сидорова</SURNAME>
	<NAME>Ирина</NAME>
	<PATRONYMIC> Анатольевна</PATRONYMIC>
	<ADDRESS>
		<INDEX>65125</INDEX>
		<TYPESETTLEMENT>Город</TYPESETTLEMENT>
		<REGION>Одесская область</REGION>
		<DISTRICT>Одесский район</DISTRICT>
		<NAMESETTLEMENT>Одесса</NAMESETTLEMENT>
		<SREET>Платанова</SREET>
		<NUMBERHOME>18</NUMBERHOME>
		<ROOM>23</ROOM>
	</ADDRESS>
	<NUMBER>
		<HOME>05761 177 84 12</HOME>
		<PHONE>+38 05761 444 23 19</PHONE>
		<PHONE>+38 05761 844 10 99</PHONE>
	</NUMBER>
	<POSITION>Аналитик</POSITION>
	<SUBVISION>Маркетинг</SUBVISION>
</EMPLOYEE>
<EMPLOYEE>
	<SURNAME>Васякин</SURNAME>
	<NAME>Виктор</NAME>
	<PATRONYMIC>Иванович</PATRONYMIC>
	<ADDRESS>
		<INDEX>65125</INDEX>
		<TYPESETTLEMENT>деревня</TYPESETTLEMENT>
		<REGION>Одесская область</REGION>
		<DISTRICT>Болградский район</DISTRICT>
		<NAMESETTLEMENT>Малиновка</NAMESETTLEMENT>
		<SREET>Школьная</SREET>
		<NUMBERHOME>20</NUMBERHOME>
		<ROOM>-</ROOM>
	</ADDRESS>
	<NUMBER>
		<HOME>05761 177 84 12</HOME>
		<PHONE>+38 05761 844 10 99</PHONE>
	</NUMBER>
	<POSITION>Бухгалтер</POSITION>
	<SUBVISION>Бухгалтерия</SUBVISION>
</EMPLOYEE>
<EMPLOYEE>
<SURNAME>Смирнов</SURNAME>
	<NAME>Сергей</NAME>
	<PATRONYMIC>Викторович</PATRONYMIC>
	<ADDRESS>
		<INDEX>65125</INDEX>
		<TYPESETTLEMENT>Город</TYPESETTLEMENT>
		<REGION>Одесская область</REGION>
		<DISTRICT>Одесский район</DISTRICT>
		<NAMESETTLEMENT>Одесса</NAMESETTLEMENT>
		<SREET>Платанова</SREET>
		<NUMBERHOME>2</NUMBERHOME>
		<HOUSING>2</HOUSING>
		<ROOM>45</ROOM>
	</ADDRESS>
	<NUMBER>
		<HOME>05761 177 84 12</HOME>
		<PHONE>+38 05761 844 10 99</PHONE>
	</NUMBER>
	<POSITION>Секретарь</POSITION>
	<SUBVISION>Бухгалтерия</SUBVISION>
</EMPLOYEE>
</DATABASE>